<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>ArchEmperorLib</AssemblyName>
    <Product>ArchEmperor Core Lib</Product>
    <Version>0.1.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>ArchEmperorLib</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Break Arts III\BepInEx\interop\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-FirstPass">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Break Arts III\BepInEx\interop\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="CoreModule">
      <HintPath>..\lib\Public\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\lib\Public\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineUI">
      <HintPath>..\lib\Public\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Steamworks">
      <HintPath>..\lib\Public\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="FusionRealtime">
      <HintPath>..\lib\Public\Fusion.Realtime.dll</HintPath>
    </Reference>
    <Reference Include="FusionRuntime">
      <HintPath>..\lib\Public\Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="FusionCommon">
      <HintPath>..\lib\Public\Fusion.Common.dll</HintPath>
    </Reference>
    <Reference Include="FusionSockets">
      <HintPath>..\lib\Public\Fusion.Sockets.dll</HintPath>
    </Reference>
    <Reference Include="FusionUnity">
      <HintPath>..\lib\Public\Fusion.Unity.dll</HintPath>
    </Reference>
    <Reference Include="InputSystem">
      <HintPath>..\lib\Public\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEnginePhysics">
      <HintPath>..\lib\Public\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineUIModule">
      <HintPath>..\lib\Public\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineJSONSerialize">
      <HintPath>..\lib\Public\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\lib\Public\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="TextMeshProUGUI">
      <HintPath>..\lib\Public\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityAddressables">
      <HintPath>..\lib\Public\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="UnityResourceManager">
      <HintPath>..\lib\Public\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngineAssetBundle">
      <HintPath>..\lib\Public\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UniverseLib">
      <HintPath>..\lib\UniverseLib.BIE.IL2CPP.Interop.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>..\lib\Public\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="DOTweenPro">
      <HintPath>..\lib\Public\DOTweenPro.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>